# Generated by Django 4.0.4 on 2022-04-20 00:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('crm', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.CharField(choices=[('10h', datetime.time(10, 0)), ('11h', datetime.time(11, 0)), ('13h', datetime.time(13, 0)), ('14h', datetime.time(14, 0)), ('15h', datetime.time(15, 0)), ('16h', datetime.time(16, 0)), ('17h', datetime.time(17, 0))], default='10', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_created=True)),
                ('horarios', models.ManyToManyField(to='api.schedulehours')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
            ],
        ),
    ]
