# Generated by Django 4.0.4 on 2022-04-20 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulehours',
            name='horarios',
            field=models.CharField(choices=[('10h', datetime.time(10, 0)), ('11h', datetime.time(11, 0)), ('13h', datetime.time(13, 0)), ('14h', datetime.time(14, 0)), ('15h', datetime.time(15, 0)), ('16h', datetime.time(16, 0)), ('17h', datetime.time(17, 0))], max_length=3, unique=True),
        ),
    ]
