# Generated by Django 4.0.4 on 2022-04-20 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_schedulehours_horarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Médico'},
        ),
        migrations.AlterModelOptions(
            name='schedulehours',
            options={'verbose_name': 'Horário'},
        ),
        migrations.AlterField(
            model_name='schedulehours',
            name='horarios',
            field=models.TimeField(choices=[(datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(15, 0), datetime.time(15, 0)), (datetime.time(16, 0), datetime.time(16, 0)), (datetime.time(17, 0), datetime.time(17, 0))], unique=True),
        ),
    ]
