# Generated by Django 4.0.4 on 2022-04-20 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_doctor_options_alter_schedulehours_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulehours',
            name='horarios',
            field=models.CharField(choices=[(datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(15, 0), datetime.time(15, 0)), (datetime.time(16, 0), datetime.time(16, 0)), (datetime.time(17, 0), datetime.time(17, 0))], max_length=100, unique=True),
        ),
    ]
