# Generated by Django 4.0.4 on 2022-04-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_schedulehours_horarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulehours',
            old_name='horarios',
            new_name='hora',
        ),
    ]
