# Generated by Django 4.0.4 on 2022-04-20 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_horarios_schedulehours_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulehours',
            old_name='hora',
            new_name='horario',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_created=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
            ],
        ),
    ]
